version: '3'

services:
  api:
    container_name: "permission-api"
    build:
      context: .
    ports:
      - "8000:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_DB}
      DB_PORT: 5432

  db:
    container_name: ${POSTGRES_DB}
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}