services:
  api:
    container_name: "permission-api"
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_HOST: "postgres"
      DB_PORT: 5432
    depends_on:
      - db

  db:
    container_name: permission_db
    image: postgres:alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - permission_db:/var/lib/postgresql/data

volumes:
  permission_db: