auth0:
  audience: "https://insgis-permission"
spring:
  application:
    name: resource-service-with-auth-example
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-yji1i5wqpyqdg0e3.us.auth0.com/"
          client-id: "6657a210c06718068a224760"
          client-secret: "8MkDH_AFX4Rig2fE_46YhLqPJjrjoZxwdvQSdB8BtYgc2pZFYtVLFIvun5i9C4Og"