name: "Continuous Deployment - DEV"
on:
  push:
    branches:
      - dev
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Short SHA
        id: short-sha
        run: echo "::set-output name=short-sha::$(git rev-parse --short=8 HEAD)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PACKAGES_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/your-github-username/ingSis-permission:latest
          build-args: |
            USERNAME=${{ secrets.PUBLISH_USERNAME }}
            TOKEN=${{ secrets.DOCKER_PACKAGES_SECRET }}

      - name: Debug information
        run: |
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
